// frontend/angular/src/app/components/login/login.component.ts
import {Component} from '@angular/core';
import {AuthRequest} from "../../models/auth-request";
import {AuthService} from "../../services/auth/auth.service";
import {Router} from "@angular/router";

@Component({
    selector: 'app-login',
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.scss']
})
export class LoginComponent {
    authRequest: AuthRequest = {};
    errorMsg = '';

    constructor(
        private authService: AuthService,
        private router: Router
    ) {
    }

    login() {
        this.errorMsg = '';
        this.authService.login(this.authRequest)
            .subscribe({
                next: (authResponse) => {
                    console.log(authResponse);
                    localStorage.setItem('access_key', JSON.stringify(authResponse));
                    this.router.navigate(['customers'])

                },
                error: (err) => {
                    if (err.error.statusCode === 401) {
                        this.errorMsg = 'Email or Password is incorrect.'
                    }
                    console.log();
                }
            });
    }

    signUp() {
        this.router.navigate(['register']);
    }
}

<div class="flex" style="height: 100vh">
    <div class="col-6 m-3 flex flex-column justify-content-center">
        <div class="m-auto">
            <div class="text-center">
                <img
                        alt="paulofranklins logo"
                        height="200px"
                        src="https://github.com/paulofranklins2/spring-boot-fullstack/blob/master/frontend/react/src/resources/image/paulofranklins-logos_black.png?raw=true">
            </div>
            <h1>Sign In.</h1>
            <p-message
                    *ngIf="errorMsg"
                    [text]="errorMsg"
                    severity="error"
                    styleClass="mb-2"
            ></p-message>
            <div class="field">
                <label for="email">Email</label>
                <input
                        [(ngModel)]="authRequest.username"
                        class="w-full"
                        id="email"
                        pInputText
                        placeholder="email@gmail.com"
                        type="email"
                >
            </div>
            <div class="field">
                <label for="password">Password</label>
                <input
                        [(ngModel)]="authRequest.password"
                        class="w-full"
                        id="password"
                        pInputText
                        placeholder="Password"
                        type="password"
                >
            </div>
            <button
                    (click)="login()"
                    class="w-full"
                    label="Login"
                    pButton
            ></button>
            <button
                    (click)="signUp()"
                    class="w-full p-button-link text-left pl-0"
                    label="Don't have an account? Sign up now."
                    pButton
            ></button>
        </div>
    </div>
    <div class="col-6 flex flex-column justify-content-center align-items-center right-container">
        <img
                class="background p-6 pt-0"
                src="https://github.com/paulofranklins2/spring-boot-fullstack/blob/master/frontend/react/src/resources/image/215539167-d7006790-b880-4929-83fb-c43fa74f429e.png?raw=true"
         alt="project image">
    </div>
</div>

// frontend/react/src/components/login/Login.jsx
import {Alert, AlertIcon, Box, Button, Flex, FormLabel, Heading, Image, Input, Link, Stack,} from '@chakra-ui/react';
import {Form, Formik, useField} from "formik";
import * as Yup from 'yup';
import {useAuth} from "../context/AuthContext.jsx";
import {errorNotification} from "../../services/Notification.js";
import {useNavigate} from "react-router-dom";
import {useEffect} from "react";

const MyTextInput = ({label, ...props}) => {
    const [field, meta] = useField(props);
    return (
        <Box>
            <FormLabel htmlFor={props.id || props.name}>{label}</FormLabel>
            <Input className="text-input" {...field} {...props} />
            {meta.touched && meta.error ? (
                <Alert className="error" status={"error"} mt={2}>
                    <AlertIcon/>
                    {meta.error}
                </Alert>
            ) : null}
        </Box>
    );
};

const LoginForm = () => {
    const { login } = useAuth();
    const navigate = useNavigate();

    return (
        <Formik
            validateOnMount={true}
            validationSchema={
                Yup.object({
                    username: Yup.string()
                        .email("Must be valid email")
                        .required("Email is required"),
                    password: Yup.string()
                        .max(20, "Password cannot be more than 20 characters")
                        .required("Password is required")
                })
            }
            initialValues={{username: '', password: ''}}
            onSubmit={(values, {setSubmitting}) => {
                setSubmitting(true);
                login(values).then(res => {
                    navigate("/dashboard")
                    console.log("Successfully logged in");
                }).catch(err => {
                    errorNotification(
                        err.code,
                        err.response.data.message
                    )
                }).finally(() => {
                    setSubmitting(false);
                })
            }}>

            {({isValid, isSubmitting}) => (
                <Form>
                    <Stack mt={15} spacing={15}>
                        <MyTextInput
                            label={"Email"}
                            name={"username"}
                            type={"email"}
                            placeholder={"email@gmail.com"}
                        />
                        <MyTextInput
                            label={"Password"}
                            name={"password"}
                            type={"password"}
                        />

                        <Button
                            type={"submit"}
                            disabled={!isValid || isSubmitting}>
                            Login
                        </Button>
                    </Stack>
                </Form>
            )}

        </Formik>
    )
}

const Login = () => {

    const { customer } = useAuth();
    const navigate = useNavigate();

    useEffect(() => {
        if (customer) {
            navigate("/dashboard/customers");
        }
    })

    return (
        <Stack minH={'100vh'} direction={{base: 'column', md: 'row'}}>
            <Flex p={8} flex={1} alignItems={'center'} justifyContent={'center'}>
                <Stack spacing={4} w={'full'} maxW={'md'}>
                    <Image
                        src='https://github.com/paulofranklins2/spring-boot-fullstack/blob/master/frontend/react/src/resources/image/paulofranklins-logos_black.png?raw=true'
                        alt='PAULOFRANKLINS'
                        boxSize={"200px"}
                        alignSelf={"center"}
                    />
                    <Heading fontSize={'2xl'} mb={15}>Sign in</Heading>
                    <LoginForm/>
                    <Link color={"blue.500"} href={"/signup"}>
                        New here? Sign up now.
                    </Link>
                </Stack>
            </Flex>
            <Flex
                flex={1}
                p={10}
                flexDirection={"column"}
                alignItems={"center"}
                justifyContent={"center"}
                bgGradient={{sm: 'linear(to-r, blue.600, purple.600)'}}
            >
                <Image
                    objectFit={'scale-down'}
                    src='https://github.com/paulofranklins2/spring-boot-fullstack/blob/master/frontend/react/src/resources/image/215539167-d7006790-b880-4929-83fb-c43fa74f429e.png?raw=true'
                    alt='PAULOFRANKLINS'
                />
            </Flex>
        </Stack>
    );
}

export default Login;
