// frontend/angular/src/app/components/customer-card/customer-card.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {CustomerDTO} from "../../models/customerDTO";

@Component({
    selector: 'app-customer-card',
    templateUrl: './customer-card.component.html',
    styleUrls: ['./customer-card.component.scss']
})
export class CustomerCardComponent {

    @Input()
    customer: CustomerDTO = {}
    @Input()
    customerIndex = 0;
    @Output()
    update: EventEmitter<CustomerDTO> = new EventEmitter<CustomerDTO>();
    @Output()
    delete: EventEmitter<CustomerDTO> = new EventEmitter<CustomerDTO>();

    get customerImage(): string {
        let gender = this.customer.gender === 'MALE' ? 'men' : 'women'
        return `https://randomuser.me/api/portraits/${gender}/${this.customerIndex}.jpg`
    }

    onDelete() {
        this.delete.emit(this.customer)
    }

    onUpdate() {
        this.update.emit(this.customer)
    }
}

<p-card
        [style]="{width: '316px'}"
        styleClass="p-card-shadow text-center">
    <ng-template pTemplate="header">
        <div>
            <img
                    alt="customer-card"
                    class="border-round-top cover"
                    height="120"
                    src="https://images.unsplash.com/photo-1612865547334-09cb8cb455da?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
            >
        </div>
        <div
                class="flex justify-content-center"
                style="margin-top: -50px"
        >
            <img
                    class="customer-avatar"
                    [src]="customerImage"
                    alt="customer-profile-avatar">
        </div>
    </ng-template>
    <ng-template pTemplate="content">
        <p-badge
                [value]="customerIndex.toString()"
        ></p-badge>
        <h2>{{ customer.name}}</h2>
        <p class="text-gray-600">{{customer.email}}</p>
        <p class="text-gray-600">{{customer.age}} | {{customer.gender}}</p>
    </ng-template>
    <ng-template pTemplate="footer">
        <button
                (click)="onUpdate()"
                class="p-button-secondary p-button-outlined p-button-rounded"
                label="Update"
                pButton

        ></button>
        <button
                (click)="onDelete()"
                class="p-button-danger p-button-outlined p-button-rounded ml-3"
                label="Delete"
                pButton
        ></button>
    </ng-template>
</p-card>

// frontend/react-api/src/components/CustomerCard.jsx
import {
    Heading,
    Avatar,
    Box,
    Center,
    Image,
    Flex,
    Text,
    Stack,
    Tag,
    useColorModeValue,
} from '@chakra-ui/react';

export default function CardWithImage({id, name, email, age, gender, imageNumber}) {
    const defineGender = gender === 'MALE' ? 'men' : 'women';
    // const imageNumber = Math.floor(Math.random() * (50 - 21) + 21)
    const profilePicture = `https://randomuser.me/api/portraits/${defineGender}/${imageNumber}.jpg`;

    return (
        <Center py={6}>
            <Box
                maxW={'300px'}
                w={'full'}
                bg={useColorModeValue('white', 'gray.800')}
                boxShadow={'2xl'}
                rounded={'md'}
                overflow={'hidden'}>
                <Image
                    h={'120px'}
                    w={'full'}
                    src={
                        'https://images.unsplash.com/photo-1612865547334-09cb8cb455da?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80'
                    }
                    objectFit={'cover'}
                />
                <Flex justify={'center'} mt={-12}>
                    <Avatar
                        size={'xl'}
                        src={
                            profilePicture
                        }
                        alt={'Author'}
                        css={{
                            border: '2px solid white',
                        }}
                    />
                </Flex>

                <Box p={6}>
                    <Stack spacing={2} align={'center'} mb={5}>
                        <Tag borderRadius={"full"}>{id}</Tag>
                        <Heading fontSize={'2xl'} fontWeight={500} fontFamily={'body'}>
                            {name}
                        </Heading>
                        <Text color={'gray.500'}>{email}</Text>
                        <Text color={'gray.500'}>Age {age} | Gender: {gender}</Text>
                    </Stack>
                </Box>
            </Box>
        </Center>
    );
}
